[package]
name = "test_wasm_call_remote_caller"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com", "freesig" ]
edition = "2018"

[lib]
name = "test_wasm_call_remote_caller"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
hdk = { path = "../../../../hdk" }
serde = "1.0.104"
